version: '3.5'

services:
  app:
    build: ./
    container_name: 'company_repository-app'
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/company_repository
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_BOOTSTRAP_SERVER=localhost:9092


  postgres:
    image: 'postgres:15.2'
    container_name: 'company_repository'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: company_repository
    ports:
      - "5432:5432"
    expose:
      - '5432'

